runtime: go116

env: standard
app_engine_apis: true
instance_class: F1
handlers:
  - url: "/favicon.ico"
    static_files: static/favicon.png
    upload: static/favicon.png

  - url: "/robots.txt"
    static_files: static/robots.txt
    upload: static/robots.txt

  - url: "/(.*\\.(gif|png|jpg))$"
    static_files: "static/\\1"
    require_matching_file: false
    upload: "static/.*\\.(gif|png|jpg)$"

  - url: '/.*'
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  MAIL_SENDER: "<YOUR_GAE_MAIL_SENDER>"
  # you can set up CUSTOM_TOKEN for enable auth check
  # if you enable, you need to add `curl -H 'Custom-Token: <YOUR_TOEKN>' `
  # CUSTOM_TOKEN: "<>YOUR_TOEKN>"
